# We create a Docker Compose file with a single service called "app"
version: "3.8"
services:
  dev-database:
    image: postgres:15.0
    container_name: dev-database
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devdb
    networks:
      - nestjs-network
    # Create another container for test
  test-database:
    image: postgres:15.0
    container_name: test-database
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    networks:
      - nestjs-network
networks:
  nestjs-network:

  #Create container, network,... from docker-compose.yaml file
  # -d: detach mode
  #docker-compose up -d
 #docker-compose up -d dev-database
 # docker log
 # how to remove container+volumes
 # docker compose rm dev-database --stop --force --volumes